version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./model_reverse.pth:/app/model_reverse.pth
    restart: unless-stopped

  frontend:
    build: ./transformer-web
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped 